# Site settings
title: kai.systems
email: kai@kai.systems
description: "A place where Kieran Hannigan puts things on the internet."
baseurl: ""
url: "http://kai.systems"

# Build settings
markdown: kramdown
permalink: pretty
